// components/AppHidden.vue
<template>
  <span @dblclick="reveal()" :style="span_style">
    {{ display_data }}
  </span>
</template>

<script>
export default {
  name: "AppHidden",
  props: {
    data: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      is_revealing: false,
    };
  },
  computed: {
    display_data() {
      return this.is_revealing ? this.data : "Double click to reveal data.";
    },
    span_style() {
      const user_select_value = ["none", "auto"];
      const cursor_value = ["pointer", "auto"];

      return {
        userSelect: user_select_value[+this.is_revealing],
        cursor: cursor_value[+this.is_revealing],
      };
    },
  },
  methods: {
    reveal() {
      this.is_revealing = !this.is_revealing;
    },
  },
};
</script>

// src/components/AppHidden.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	export let data: string = '';

	let is_mounted = false;
	let is_revealing = false;
	$: display_data = is_revealing ? data : 'Double click to reveal data.';
	$: span_style = (() => {
		const user_select_value = ['none', 'auto'];
		const cursor_value = ['pointer', 'auto'];
		const formatted = `user-select:${user_select_value[+is_revealing]};cursor:${
			cursor_value[+is_revealing]
		}`;

		return is_mounted ? formatted : `display:none;${formatted}`;
	})();

	const reveal = () => {
		is_revealing = !is_revealing;
	};

	onMount(() => (is_mounted = true));
</script>

<span on:dblclick={reveal} style={`${span_style}`}>
	{display_data}
</span>
<noscript>
	<span>Please enable JavaScript to see the email.</span>
</noscript>
